# Generated by Django 3.0.8 on 2020-07-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('booked', models.BooleanField()),
            ],
        ),
    ]
