# Generated by Django 3.0.8 on 2020-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_auto_20200720_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cars',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
