# Generated by Django 3.0.8 on 2020-07-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_auto_20200720_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='userId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
